name: build
on:
  pull_request:
    # branches: [ main ]
  schedule:
    - cron: '1 8 * * *'
jobs:
  build-docker-images:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution: ["jazzy", "kilted", "rolling"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build rmf image and push to gh registry
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distribution }}
          tags: ghcr.io/${{ github.repository }}/rmf_demos:${{ matrix.ros_distribution }}-rmf-latest
          context: .
